version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=david
      - POSTGRES_DB=database
    ports:
      - '5433:5432'

  jenkins:
     image: jenkins/jenkins:lts
     privileged: true
     user: root
     ports:
     - 8080:8080
     - 50000:50000
     container_name: jenkins
     volumes:
       - /home/david/jenkins_compose/jenkins_configuration:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock

  demo:
    container_name: demo_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/database
      - SPRING_DATASOURCE_USERNAME=david
      - SPRING_DATASOURCE_PASSWORD=david
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
      - jenkins
