version: "3.8"

volumes:
  pgdata:

services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=david
      - POSTGRES_DB=database
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - '8080:8080'
     - '50000:50000'
    container_name: jenkins
    volumes:
      - /home/david/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    container_name: rest_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/database
      - SPRING_DATASOURCE_USERNAME=david
      - SPRING_DATASOURCE_PASSWORD=david
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
      - jenkins
